import { Chamber, PoliticalParty, Legislator } from "./types";

export const EXTENDED_LEGISLATORS: Legislator[] = [
  {
    id: "leg-moro",
    name: "Sen. Abba Moro",
    title: "Senator",
    chamber: Chamber.SENATE,
    state: "Benue",
    constituency: "Benue South",
    party: PoliticalParty.PDP,
    engagementScore: 84,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 92,
    motionsPresentedCount: 15,
    districtOfficeEmail: "a.moro@senate.gov.ng",
    status: "Active"
  },
  {
    id: "leg-ningi-sen",
    name: "Sen. Abdul Ningi",
    title: "Senator",
    chamber: Chamber.SENATE,
    state: "Bauchi",
    constituency: "Bauchi Central",
    party: PoliticalParty.PDP,
    engagementScore: 82,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 91,
    motionsPresentedCount: 16,
    districtOfficeEmail: "a.ningi@senate.gov.ng",
    status: "Active"
  },
  {
    id: "leg-yari-sen",
    name: "Sen. Abdulaziz Yari",
    title: "Senator",
    chamber: Chamber.SENATE,
    state: "Zamfara",
    constituency: "Zamfara West",
    party: PoliticalParty.APC,
    engagementScore: 85,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 93,
    motionsPresentedCount: 11,
    districtOfficeEmail: "a.yari@senate.gov.ng",
    status: "Active"
  },
  {
    id: "leg-ado-rep",
    name: "Hon. Abdulhakeem Kamilu Ado",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Kano",
    constituency: "Wudil/Garko",
    party: PoliticalParty.NNPP,
    engagementScore: 78,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 88,
    motionsPresentedCount: 4,
    districtOfficeEmail: "k.ado@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-danbuya-rep",
    name: "Hon. Abdulkadir Danbuya",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Sokoto",
    constituency: "Isa/Sabon Birni",
    party: PoliticalParty.APC,
    engagementScore: 81,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 89,
    motionsPresentedCount: 7,
    districtOfficeEmail: "a.danbuya@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-rahis-rep",
    name: "Hon. Abdulkadir Rahis",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Borno",
    constituency: "Maiduguri (Metropolitan)",
    party: PoliticalParty.APC,
    engagementScore: 85,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 92,
    motionsPresentedCount: 14,
    districtOfficeEmail: "a.rahis@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-dabai-rep",
    name: "Hon. Abdullahi Dabai",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Katsina",
    constituency: "Bakori/Danja",
    party: PoliticalParty.PDP,
    engagementScore: 79,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 90,
    motionsPresentedCount: 5,
    districtOfficeEmail: "a.dabai@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-ali-rep",
    name: "Hon. Abdullahi Ibrahim Ali",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Kogi",
    constituency: "Ankpa/Omala/Olamaboro",
    party: PoliticalParty.APC,
    engagementScore: 83,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 91,
    motionsPresentedCount: 9,
    districtOfficeEmail: "a.ali@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-garba-rep",
    name: "Hon. Abdullahi Idris Garba",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Niger",
    constituency: "Kontagora/Wushishi/Mariga/Mashegu",
    party: PoliticalParty.APC,
    engagementScore: 87,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 94,
    motionsPresentedCount: 12,
    districtOfficeEmail: "a.garba@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-mamudu-rep",
    name: "Hon. Abdullahi Mamudu",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Niger",
    constituency: "Agaie/Lapai",
    party: PoliticalParty.APC,
    engagementScore: 82,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 90,
    motionsPresentedCount: 10,
    districtOfficeEmail: "a.mamudu@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-sani-rep",
    name: "Hon. Abdullahi Sani",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Kano",
    constituency: "Karaye/Rogo",
    party: PoliticalParty.NNPP,
    engagementScore: 80,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 88,
    motionsPresentedCount: 6,
    districtOfficeEmail: "a.sani@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-zubairu-rep",
    name: "Hon. Abdulmalik Zubairu",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Zamfara",
    constituency: "Bungudu/Maru",
    party: PoliticalParty.APC,
    engagementScore: 82,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 89,
    motionsPresentedCount: 8,
    districtOfficeEmail: "a.zubairu@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-ari-rep",
    name: "Hon. Abdulmumin Ari Mohammed",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Nasarawa",
    constituency: "Nassarawa/Toto",
    party: PoliticalParty.APC,
    engagementScore: 83,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 91,
    motionsPresentedCount: 11,
    districtOfficeEmail: "a.mohammed@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-maleek-rep",
    name: "Hon. Abdulraheem Abdulmaleek",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Kogi",
    constituency: "Adavi/Okehi",
    party: PoliticalParty.PDP,
    engagementScore: 80,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 89,
    motionsPresentedCount: 7,
    districtOfficeEmail: "a.maleek@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-olawuyi-rep",
    name: "Hon. Abdulraheem Olatunji Olawuyi",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Kwara",
    constituency: "Ekiti/Isin/Irepodun/Oke-Ero",
    party: PoliticalParty.APC,
    engagementScore: 82,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 91,
    motionsPresentedCount: 10,
    districtOfficeEmail: "o.olawuyi@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-ajiya-rep",
    name: "Hon. Abdulrahman Ajiya",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "FCT",
    constituency: "Abaji/Gwagwalada/Kwali/Kuje",
    party: PoliticalParty.APC,
    engagementScore: 84,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 93,
    motionsPresentedCount: 9,
    districtOfficeEmail: "a.ajiya@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-suleiman-sen",
    name: "Sen. Abdulrahman Kawu Suleiman",
    title: "Senator",
    chamber: Chamber.SENATE,
    state: "Kano",
    constituency: "KANO SOUTH",
    party: PoliticalParty.NNPP,
    engagementScore: 88,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 94,
    motionsPresentedCount: 15,
    districtOfficeEmail: "k.suleiman@senate.gov.ng",
    status: "Active"
  },
  {
    id: "leg-dasuki-rep",
    name: "Hon. Abdussamad Ibrahim Dasuki",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Sokoto",
    constituency: "Kebbe/Tambuwal",
    party: PoliticalParty.PDP,
    engagementScore: 83,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 91,
    motionsPresentedCount: 12,
    districtOfficeEmail: "i.dasuki@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-akinlade-rep",
    name: "Hon. Abiodun Isiaq Akinlade",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Ogun",
    constituency: "Egbado South/Ipokia",
    party: PoliticalParty.APC,
    engagementScore: 81,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 90,
    motionsPresentedCount: 8,
    districtOfficeEmail: "a.akinlade@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-faleke-rep",
    name: "Hon. Abiodun James Faleke",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Lagos",
    constituency: "Ikeja",
    party: PoliticalParty.APC,
    engagementScore: 86,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 93,
    motionsPresentedCount: 14,
    districtOfficeEmail: "j.faleke@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-makinde-rep",
    name: "Hon. Abiola Peter Makinde",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Ondo",
    constituency: "Ondo East/Ondo West",
    party: PoliticalParty.APC,
    engagementScore: 84,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 91,
    motionsPresentedCount: 10,
    districtOfficeEmail: "p.makinde@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-obuku-rep",
    name: "Hon. Abonsizibe Oforji Obuku",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Bayelsa",
    constituency: "Yenagoa/Kolokuna/Opokuma",
    party: PoliticalParty.PDP,
    engagementScore: 79,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 88,
    motionsPresentedCount: 6,
    districtOfficeEmail: "o.obuku@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-abubakar-rep",
    name: "Hon. Abubakar Ahmad Mohammed",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Katsina",
    constituency: "Funtua/Dandume",
    party: PoliticalParty.APC,
    engagementScore: 80,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 89,
    motionsPresentedCount: 7,
    districtOfficeEmail: "a.abubakar@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-fulata-rep",
    name: "Hon. Abubakar Hassan Fulata",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Jigawa",
    constituency: "Birniwa Guri/Kirikasamma",
    party: PoliticalParty.APC,
    engagementScore: 85,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 93,
    motionsPresentedCount: 13,
    districtOfficeEmail: "h.fulata@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-nalaraba-rep",
    name: "Hon. Abubakar Hassan Nalaraba",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Nasarawa",
    constituency: "Awe/Doma/Keana",
    party: PoliticalParty.APC,
    engagementScore: 84,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 92,
    motionsPresentedCount: 11,
    districtOfficeEmail: "h.nalaraba@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-kabir-rep",
    name: "Hon. Abubakar Kabir Abubakar",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Kano",
    constituency: "Bichi",
    party: PoliticalParty.APC,
    engagementScore: 86,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 94,
    motionsPresentedCount: 12,
    districtOfficeEmail: "k.abubakar@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-sarki-rep",
    name: "Hon. Abubakar Sarki Dahiru",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Nasarawa",
    constituency: "Lafia/Obi",
    party: PoliticalParty.OTHER,
    engagementScore: 81,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 90,
    motionsPresentedCount: 9,
    districtOfficeEmail: "s.dahiru@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-yabo-rep",
    name: "Hon. Abubakar Yabo Umaru",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Sokoto",
    constituency: "Yabo/Shagari",
    party: PoliticalParty.APC,
    engagementScore: 82,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 90,
    motionsPresentedCount: 7,
    districtOfficeEmail: "y.umaru@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-kusada-rep",
    name: "Hon. Abubakar Yahaya Kusada",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Katsina",
    constituency: "Ingawa/Kankia/Kusada",
    party: PoliticalParty.APC,
    engagementScore: 83,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 91,
    motionsPresentedCount: 10,
    districtOfficeEmail: "y.kusada@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-hashimu-rep",
    name: "Hon. Adamu Hashimu",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Bauchi",
    constituency: "Ningi/Warji",
    party: PoliticalParty.PDP,
    engagementScore: 80,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 89,
    motionsPresentedCount: 8,
    districtOfficeEmail: "a.hashimu@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-gamawa-rep",
    name: "Hon. Adamu Ibrahim Gamawa",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Bauchi",
    constituency: "Gamawa",
    party: PoliticalParty.APC,
    engagementScore: 81,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 90,
    motionsPresentedCount: 6,
    districtOfficeEmail: "i.gamawa@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-tanko-rep",
    name: "Hon. Adamu Tanko",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Niger",
    constituency: "Gurara/Suleja/Tapa",
    party: PoliticalParty.PDP,
    engagementScore: 82,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 91,
    motionsPresentedCount: 9,
    districtOfficeEmail: "a.tanko@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-adaramodu-sen",
    name: "Sen. Adaramodu Adeyemi Raphael",
    title: "Senator",
    chamber: Chamber.SENATE,
    state: "Ekiti",
    constituency: "EKITI SOUTH",
    party: PoliticalParty.APC,
    engagementScore: 86,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 93,
    motionsPresentedCount: 11,
    districtOfficeEmail: "y.adaramodu@senate.gov.ng",
    status: "Active"
  },
  {
    id: "leg-balogun-rep",
    name: "Hon. Adebayo Olusegun Balogun",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Lagos",
    constituency: "Ibeju Lekki",
    party: PoliticalParty.APC,
    engagementScore: 81,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 90,
    motionsPresentedCount: 8,
    districtOfficeEmail: "o.balogun@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-kalejaiye-rep",
    name: "Hon. Adeboye Paul Kalejaiye",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Lagos",
    constituency: "Ajeromi/Ifelodun",
    party: PoliticalParty.APC,
    engagementScore: 82,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 91,
    motionsPresentedCount: 7,
    districtOfficeEmail: "p.kalejaiye@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-adebule-sen",
    name: "Sen. Adebule Idiat Oluranti",
    title: "Senator",
    chamber: Chamber.SENATE,
    state: "Lagos",
    constituency: "LAGOS WEST",
    party: PoliticalParty.APC,
    engagementScore: 88,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 95,
    motionsPresentedCount: 13,
    districtOfficeEmail: "i.adebule@senate.gov.ng",
    status: "Active"
  },
  {
    id: "leg-adesola-rep",
    name: "Hon. Adedayo Samuel Adesola",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Lagos",
    constituency: "Apapa",
    party: PoliticalParty.APC,
    engagementScore: 83,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 90,
    motionsPresentedCount: 8,
    districtOfficeEmail: "s.adesola@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-olajide-rep",
    name: "Hon. Adedeji Stanley Olajide",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Oyo",
    constituency: "Ibadan South West/Ibadan North West",
    party: PoliticalParty.PDP,
    engagementScore: 82,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 91,
    motionsPresentedCount: 11,
    districtOfficeEmail: "s.olajide@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-adefarati-rep",
    name: "Hon. Adefarati Adegboyega",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Ondo",
    constituency: "Akoko South East/Akoko South West",
    party: PoliticalParty.APC,
    engagementScore: 81,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 90,
    motionsPresentedCount: 7,
    districtOfficeEmail: "a.adefarati@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-adelegbe-rep",
    name: "Hon. Adelegbe Emmanuel Oluwatimehin",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Ondo",
    constituency: "Owo/Ose",
    party: PoliticalParty.APC,
    engagementScore: 83,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 92,
    motionsPresentedCount: 9,
    districtOfficeEmail: "e.adelegbe@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-adegbonmire-sen",
    name: "Sen. Adeniyi Adegbonmire",
    title: "Senator",
    chamber: Chamber.SENATE,
    state: "Ondo",
    constituency: "ONDO CENTRAL",
    party: PoliticalParty.APC,
    engagementScore: 85,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 92,
    motionsPresentedCount: 11,
    districtOfficeEmail: "a.adegbonmire@senate.gov.ng",
    status: "Active"
  },
  {
    id: "leg-oseni-rep",
    name: "Hon. Aderemi Abasi Oseni",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Oyo",
    constituency: "Ibarapa East/Ido",
    party: PoliticalParty.APC,
    engagementScore: 82,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 90,
    motionsPresentedCount: 8,
    districtOfficeEmail: "a.oseni@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-adesida-rep",
    name: "Hon. Adesida Abiodun",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Ondo",
    constituency: "Akure North/Akure South",
    party: PoliticalParty.APC,
    engagementScore: 83,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 91,
    motionsPresentedCount: 9,
    districtOfficeEmail: "a.adesida@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-elegbeji-rep",
    name: "Hon. Adesola Ayoola Elegbeji",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Ogun",
    constituency: "Ikenne/Shagamu/Remo North",
    party: PoliticalParty.APC,
    engagementScore: 81,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 90,
    motionsPresentedCount: 6,
    districtOfficeEmail: "a.elegbeji@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-abiru-sen",
    name: "Sen. Adetokunbo Mukhail Abiru",
    title: "Senator",
    chamber: Chamber.SENATE,
    state: "Lagos",
    constituency: "LAGOS EAST",
    party: PoliticalParty.APC,
    engagementScore: 89,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 96,
    motionsPresentedCount: 14,
    districtOfficeEmail: "t.abiru@senate.gov.ng",
    status: "Active"
  },
  {
    id: "leg-ogbara-rep",
    name: "Hon. Adetola Kafilat Ogbara",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Lagos",
    constituency: "Kosofe",
    party: PoliticalParty.APC,
    engagementScore: 84,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 92,
    motionsPresentedCount: 11,
    districtOfficeEmail: "k.ogbara@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-olusoji-rep",
    name: "Hon. Adetunji Abidemi Olusoji",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Osun",
    constituency: "Odo-Otin/Ifelodun/Boripe",
    party: PoliticalParty.PDP,
    engagementScore: 82,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 91,
    motionsPresentedCount: 10,
    districtOfficeEmail: "a.olusoji@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-hameed-rep",
    name: "Hon. Adewale Hameed",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Lagos",
    constituency: "Agege",
    party: PoliticalParty.APC,
    engagementScore: 83,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 91,
    motionsPresentedCount: 8,
    districtOfficeEmail: "h.adewale@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-onanuga-rep",
    name: "Hon. Adewunmi Oriyomi Onanuga",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Ogun",
    constituency: "Ikenne/Sagamu/Remo North",
    party: PoliticalParty.APC,
    engagementScore: 84,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 92,
    motionsPresentedCount: 12,
    districtOfficeEmail: "o.onanuga@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-olabinjo-rep",
    name: "Hon. Adeyemi Benjamin Olabinjo",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Lagos",
    constituency: "Ifako/Ijaiye",
    party: PoliticalParty.APC,
    engagementScore: 82,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 91,
    motionsPresentedCount: 9,
    districtOfficeEmail: "b.olabinjo@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-taofeek-rep",
    name: "Hon. Adeyemi Taofeek Alli",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Lagos",
    constituency: "Mushin I",
    party: PoliticalParty.APC,
    engagementScore: 83,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 91,
    motionsPresentedCount: 8,
    districtOfficeEmail: "t.alli@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-afam-rep",
    name: "Hon. Afam Ogene",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Anambra",
    constituency: "Ogbaru",
    party: PoliticalParty.LP,
    engagementScore: 85,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 93,
    motionsPresentedCount: 12,
    districtOfficeEmail: "a.ogene@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-afuape-rep",
    name: "Hon. Afolabi Moruf Afuape",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Ogun",
    constituency: "Abeokuta South",
    party: PoliticalParty.APC,
    engagementScore: 82,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 91,
    motionsPresentedCount: 9,
    districtOfficeEmail: "m.afuape@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-salisu-sen",
    name: "Sen. Afolabi Salisu",
    title: "Senator",
    chamber: Chamber.SENATE,
    state: "Ogun",
    constituency: "OGUN CENTRAL",
    party: PoliticalParty.APC,
    engagementScore: 86,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 93,
    motionsPresentedCount: 10,
    districtOfficeEmail: "s.salisu@senate.gov.ng",
    status: "Active"
  },
  {
    id: "leg-musa-rep",
    name: "Hon. Agah Avia Musa",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Plateau",
    constituency: "Jos North/Bassa",
    party: PoliticalParty.PDP,
    engagementScore: 81,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 90,
    motionsPresentedCount: 8,
    districtOfficeEmail: "a.musa@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-agbedi-rep",
    name: "Hon. Agbedi Yeitiemone Frederick",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Bayelsa",
    constituency: "Sagbama/Ekeremor",
    party: PoliticalParty.PDP,
    engagementScore: 84,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 92,
    motionsPresentedCount: 14,
    districtOfficeEmail: "f.agbedi@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-kalambaina-rep",
    name: "Hon. Ahmad Abdullahi Kalambaina",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Sokoto",
    constituency: "Kware/Wamakko",
    party: PoliticalParty.APC,
    engagementScore: 82,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 91,
    motionsPresentedCount: 9,
    districtOfficeEmail: "a.kalambaina@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-lawan-sen",
    name: "Sen. Ahmad Lawan",
    title: "Senator",
    chamber: Chamber.SENATE,
    state: "Yobe",
    constituency: "YOBE NORTH",
    party: PoliticalParty.APC,
    engagementScore: 91,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 98,
    motionsPresentedCount: 16,
    districtOfficeEmail: "a.lawan@senate.gov.ng",
    status: "Active"
  },
  {
    id: "leg-jaha-rep",
    name: "Hon. Ahmadu Usman Jaha",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Borno",
    constituency: "Damboa/Gwoza/Chibok",
    party: PoliticalParty.APC,
    engagementScore: 86,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 94,
    motionsPresentedCount: 15,
    districtOfficeEmail: "u.jaha@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-saba-rep",
    name: "Hon. Ahmed Adamu Saba",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Kwara",
    constituency: "Edu/Moro/Pategi",
    party: PoliticalParty.APC,
    engagementScore: 82,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 90,
    motionsPresentedCount: 8,
    districtOfficeEmail: "a.saba@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-aliyu-rep",
    name: "Hon. Ahmed Aliyu",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Katsina",
    constituency: "Matazu/Musawa",
    party: PoliticalParty.APC,
    engagementScore: 81,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 90,
    motionsPresentedCount: 7,
    districtOfficeEmail: "a.aliyu@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-doro-rep",
    name: "Hon. Ahmed Doro Yusuf",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Katsina",
    constituency: "Bindawa/Mani",
    party: PoliticalParty.APC,
    engagementScore: 81,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 90,
    motionsPresentedCount: 6,
    districtOfficeEmail: "y.doro@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-wase-rep",
    name: "Hon. Ahmed Idris Wase",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Plateau",
    constituency: "Wase",
    party: PoliticalParty.APC,
    engagementScore: 88,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 95,
    motionsPresentedCount: 16,
    districtOfficeEmail: "i.wase@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-munir-rep",
    name: "Hon. Ahmed Munir",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Kaduna",
    constituency: "Lere",
    party: PoliticalParty.APC,
    engagementScore: 83,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 91,
    motionsPresentedCount: 11,
    districtOfficeEmail: "a.munir@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-aluko-rep",
    name: "Hon. Ahmed Yinka Aluko",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Kwara",
    constituency: "Ilorin East/Ilorin South",
    party: PoliticalParty.APC,
    engagementScore: 84,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 92,
    motionsPresentedCount: 10,
    districtOfficeEmail: "y.aluko@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-umar-rep",
    name: "Hon. Ajilo Umar",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Kaduna",
    constituency: "Makarfi/Kudan",
    party: PoliticalParty.PDP,
    engagementScore: 80,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 89,
    motionsPresentedCount: 7,
    districtOfficeEmail: "u.ajilo@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-ademola-rep",
    name: "Hon. Akanni Clement Ademola",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Osun",
    constituency: "Boluwaduro/Ifedayo/Ila",
    party: PoliticalParty.PDP,
    engagementScore: 81,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 90,
    motionsPresentedCount: 9,
    districtOfficeEmail: "c.akanni@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-badru-rep",
    name: "Hon. Akanni Enitan Dolapo-badru",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Lagos",
    constituency: "Lagos Island I",
    party: PoliticalParty.APC,
    engagementScore: 85,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 93,
    motionsPresentedCount: 14,
    districtOfficeEmail: "e.dolapobadru@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-tosan-rep",
    name: "Hon. Akarachi Etinosa Tosan",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Imo",
    constituency: "Ikeduru/Mbaitoli",
    party: PoliticalParty.APC,
    engagementScore: 82,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 90,
    motionsPresentedCount: 8,
    districtOfficeEmail: "e.tosan@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-akeem-rep",
    name: "Hon. Akeem Adeniyi Adeyemi",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Oyo",
    constituency: "Afijio/Oyo East/Oyo West/Atiba",
    party: PoliticalParty.APC,
    engagementScore: 85,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 92,
    motionsPresentedCount: 11,
    districtOfficeEmail: "a.adeyemi@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-ekpenyong-rep",
    name: "Hon. Akiba Bassey Ekpenyong",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Cross River",
    constituency: "Calabar Municipal/Odukpani",
    party: PoliticalParty.LP,
    engagementScore: 83,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 91,
    motionsPresentedCount: 10,
    districtOfficeEmail: "b.ekpenyong@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-alabi-rep",
    name: "Hon. Akinola Adekunle Alabi",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Oyo",
    constituency: "Egbeda/Ona-Ara",
    party: PoliticalParty.APC,
    engagementScore: 84,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 91,
    motionsPresentedCount: 12,
    districtOfficeEmail: "a.alabi@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-rotimi-rep",
    name: "Hon. Akintunde Rotimi",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Ekiti",
    constituency: "Ikole/Oye",
    party: PoliticalParty.APC,
    engagementScore: 85,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 93,
    motionsPresentedCount: 15,
    districtOfficeEmail: "a.rotimi@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-yunus-sen",
    name: "Sen. Akintunde Yunus Abiodun",
    title: "Senator",
    chamber: Chamber.SENATE,
    state: "Oyo",
    constituency: "OYO CENTRAL",
    party: PoliticalParty.APC,
    engagementScore: 86,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 93,
    motionsPresentedCount: 11,
    districtOfficeEmail: "y.akintunde@senate.gov.ng",
    status: "Active"
  },
  {
    id: "leg-peter-rep",
    name: "Hon. Akpatason Ohiozojeh Peter",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Edo",
    constituency: "Akoko-Edo",
    party: PoliticalParty.APC,
    engagementScore: 84,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 91,
    motionsPresentedCount: 13,
    districtOfficeEmail: "p.akpatason@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-natasha-sen",
    name: "Sen. Akpoti-Uduaghan Natasha",
    title: "Senator",
    chamber: Chamber.SENATE,
    state: "Kogi",
    constituency: "KOGI CENTRAL",
    party: PoliticalParty.OTHER,
    engagementScore: 92,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 96,
    motionsPresentedCount: 19,
    districtOfficeEmail: "n.akpoti@senate.gov.ng",
    status: "Active"
  },
  {
    id: "leg-egbona-rep",
    name: "Hon. Alex Egbona",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Cross River",
    constituency: "Yakurr/Abi",
    party: PoliticalParty.PDP,
    engagementScore: 82,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 90,
    motionsPresentedCount: 9,
    districtOfficeEmail: "a.egbona@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-mascot-rep",
    name: "Hon. Alexander Mascot Ikwechegh",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Abia",
    constituency: "Aba North/Aba South",
    party: PoliticalParty.LP,
    engagementScore: 83,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 91,
    motionsPresentedCount: 11,
    districtOfficeEmail: "m.ikwechegh@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-alhassan-rep",
    name: "Hon. Alhassan Ado Garba",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Kano",
    constituency: "Doguwa/Tudun Wada",
    party: PoliticalParty.APC,
    engagementScore: 84,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 92,
    motionsPresentedCount: 14,
    districtOfficeEmail: "g.alhassan@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-ali-rep-2",
    name: "Hon. Ali Ibrahim Abdullahi",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Kogi",
    constituency: "Ankpa/Omala/Olamaboro",
    party: PoliticalParty.APC,
    engagementScore: 83,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 91,
    motionsPresentedCount: 9,
    districtOfficeEmail: "i.ali@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-isa-rep",
    name: "Hon. Ali Isa",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Gombe",
    constituency: "Balanga/Billiri",
    party: PoliticalParty.PDP,
    engagementScore: 85,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 93,
    motionsPresentedCount: 18,
    districtOfficeEmail: "i.ali@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-kuye-rep",
    name: "Hon. Aliu Ademorin Kuye",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Lagos",
    constituency: "Shomolu",
    party: PoliticalParty.APC,
    engagementScore: 83,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 91,
    motionsPresentedCount: 10,
    districtOfficeEmail: "a.kuye@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-wadada-sen",
    name: "Sen. Aliu, Wadada Ahmed",
    title: "Senator",
    chamber: Chamber.SENATE,
    state: "Nasarawa",
    constituency: "NASSARAWA WEST",
    party: PoliticalParty.APC,
    engagementScore: 87,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 94,
    motionsPresentedCount: 13,
    districtOfficeEmail: "w.aliu@senate.gov.ng",
    status: "Active"
  },
  {
    id: "leg-bappa-rep",
    name: "Hon. Aliyu Bappa misau",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Bauchi",
    constituency: "Misau/Dambam",
    party: PoliticalParty.PDP,
    engagementScore: 82,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 90,
    motionsPresentedCount: 8,
    districtOfficeEmail: "b.aliyu@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-betara-rep",
    name: "Hon. Aliyu Betara Muktar",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Borno",
    constituency: "Biu/Kwaya-Kusar, Shani/Bayo",
    party: PoliticalParty.APC,
    engagementScore: 89,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 95,
    motionsPresentedCount: 15,
    districtOfficeEmail: "m.aliyu@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-iliyasu-rep",
    name: "Hon. Aliyu Iliyasu",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Katsina",
    constituency: "Batsari/Safana/Danmusa",
    party: PoliticalParty.APC,
    engagementScore: 81,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 89,
    motionsPresentedCount: 7,
    districtOfficeEmail: "i.aliyu@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-wamakko-sen",
    name: "Sen. Aliyu Magatakarda Wamakko",
    title: "Senator",
    chamber: Chamber.SENATE,
    state: "Sokoto",
    constituency: "SOKOTO NORTH",
    party: PoliticalParty.APC,
    engagementScore: 88,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 95,
    motionsPresentedCount: 14,
    districtOfficeEmail: "m.aliyu@senate.gov.ng",
    status: "Active"
  },
  {
    id: "leg-abdullahi-rep-2",
    name: "Hon. Aliyu Mustapha Abdullahi",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Kaduna",
    constituency: "Ikara/Kubau",
    party: PoliticalParty.APC,
    engagementScore: 82,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 90,
    motionsPresentedCount: 9,
    districtOfficeEmail: "m.aliyu@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-madaki-rep",
    name: "Hon. Aliyu Sani Madaki",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Kano",
    constituency: "Dala",
    party: PoliticalParty.NNPP,
    engagementScore: 86,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 94,
    motionsPresentedCount: 16,
    districtOfficeEmail: "s.aliyu@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-boya-rep",
    name: "Hon. Aliyu Wakili Boya",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Adamawa",
    constituency: "Furore/Song",
    party: PoliticalParty.APC,
    engagementScore: 84,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 92,
    motionsPresentedCount: 11,
    districtOfficeEmail: "w.aliyu@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-sharafadeen-sen",
    name: "Sen. Alli Sharafadeen Abiodun",
    title: "Senator",
    chamber: Chamber.SENATE,
    state: "Oyo",
    constituency: "OYO SOUTH",
    party: PoliticalParty.APC,
    engagementScore: 85,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 91,
    motionsPresentedCount: 10,
    districtOfficeEmail: "s.alli@senate.gov.ng",
    status: "Active"
  },
  {
    id: "leg-anderson-rep",
    name: "Hon. Allison Igbiks Anderson",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Rivers",
    constituency: "Okrika/Ogu-Bolo",
    party: PoliticalParty.APC,
    engagementScore: 81,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 90,
    motionsPresentedCount: 8,
    districtOfficeEmail: "i.allison@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-onyesoh-sen",
    name: "Sen. Allwell Heacho Onyesoh",
    title: "Senator",
    chamber: Chamber.SENATE,
    state: "Rivers",
    constituency: "RIVERS EAST",
    party: PoliticalParty.PDP,
    engagementScore: 86,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 93,
    motionsPresentedCount: 12,
    districtOfficeEmail: "h.onyesoh@senate.gov.ng",
    status: "Active"
  },
  {
    id: "leg-chindo-rep",
    name: "Hon. Aminu Chindo",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Katsina",
    constituency: "Katsina",
    party: PoliticalParty.PDP,
    engagementScore: 80,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 89,
    motionsPresentedCount: 7,
    districtOfficeEmail: "c.aminu@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-garu-rep",
    name: "Hon. Aminu Garu Alyi",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Bauchi",
    constituency: "Bauchi",
    party: PoliticalParty.PDP,
    engagementScore: 81,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 90,
    motionsPresentedCount: 8,
    districtOfficeEmail: "g.aminu@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-abbas-sen",
    name: "Sen. Aminu Iya Abbas",
    title: "Senator",
    chamber: Chamber.SENATE,
    state: "Adamawa",
    constituency: "ADAMAWA CENTRAL",
    party: PoliticalParty.PDP,
    engagementScore: 85,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 92,
    motionsPresentedCount: 11,
    districtOfficeEmail: "i.abbas@senate.gov.ng",
    status: "Active"
  },
  {
    id: "leg-jaji-rep",
    name: "Hon. Aminu Jaji",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Zamfara",
    constituency: "Kaura-Namoda/Birnin Magaji",
    party: PoliticalParty.APC,
    engagementScore: 83,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 91,
    motionsPresentedCount: 10,
    districtOfficeEmail: "a.jaji@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-daura-rep",
    name: "Hon. Aminu Jamo Daura",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Katsina",
    constituency: "Daura/Sandamu/Mai’adua",
    party: PoliticalParty.APC,
    engagementScore: 82,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 90,
    motionsPresentedCount: 9,
    districtOfficeEmail: "j.daura@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-ogah-rep",
    name: "Hon. Amobi Ogah",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Abia",
    constituency: "Isuikwuato/Umu-Nneochi",
    party: PoliticalParty.LP,
    engagementScore: 84,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 92,
    motionsPresentedCount: 13,
    districtOfficeEmail: "a.ogah@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-magaji-rep",
    name: "Hon. Amos Gwamna Magaji",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Kaduna",
    constituency: "Zangon Kataf/Jaba",
    party: PoliticalParty.APC,
    engagementScore: 82,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 90,
    motionsPresentedCount: 8,
    districtOfficeEmail: "g.magaji@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-nwonu-rep",
    name: "Hon. Anayo Edwin Nwonu",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Ebonyi",
    constituency: "Ezza North/Ishielu",
    party: PoliticalParty.PDP,
    engagementScore: 81,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 90,
    motionsPresentedCount: 7,
    districtOfficeEmail: "e.nwonu@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-okorie-sen",
    name: "Sen. Ani Anthony Okorie",
    title: "Senator",
    chamber: Chamber.SENATE,
    state: "Ebonyi",
    constituency: "EBONYI SOUTH",
    party: PoliticalParty.APC,
    engagementScore: 84,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 91,
    motionsPresentedCount: 9,
    districtOfficeEmail: "a.okorie@senate.gov.ng",
    status: "Active"
  },
  {
    id: "leg-adepoju-rep",
    name: "Hon. Anthony Adebayo Adepoju",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Oyo",
    constituency: "Ibarapa Central/Ibarapa North",
    party: PoliticalParty.PDP,
    engagementScore: 82,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 91,
    motionsPresentedCount: 10,
    districtOfficeEmail: "a.adepoju@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-yaro-sen",
    name: "Sen. Anthony Siyako Yaro",
    title: "Senator",
    chamber: Chamber.SENATE,
    state: "Gombe",
    constituency: "GOMBE SOUTH",
    party: PoliticalParty.APC,
    engagementScore: 85,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 92,
    motionsPresentedCount: 11,
    districtOfficeEmail: "s.yaro@senate.gov.ng",
    status: "Active"
  },
  {
    id: "leg-yisa-sen",
    name: "Sen. Ashiru Oyelola Yisa",
    title: "Senator",
    chamber: Chamber.SENATE,
    state: "Kwara",
    constituency: "Kwara South",
    party: PoliticalParty.APC,
    engagementScore: 87,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 94,
    motionsPresentedCount: 14,
    districtOfficeEmail: "o.ashiru@senate.gov.ng",
    status: "Active"
  },
  {
    id: "leg-ekpenyong-sen",
    name: "Sen. Asuquo, Ekpenyong",
    title: "Senator",
    chamber: Chamber.SENATE,
    state: "Cross River",
    constituency: "CROSS RIVER SOUTH",
    party: PoliticalParty.APC,
    engagementScore: 88,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 93,
    motionsPresentedCount: 12,
    districtOfficeEmail: "e.asuquo@senate.gov.ng",
    status: "Active"
  },
  {
    id: "leg-akobundu-sen",
    name: "Sen. Augustine Okwudiri Akobundu",
    title: "Senator",
    chamber: Chamber.SENATE,
    state: "Abia",
    constituency: "ABIA CENTRAL",
    party: PoliticalParty.OTHER,
    engagementScore: 83,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 90,
    motionsPresentedCount: 8,
    districtOfficeEmail: "o.akobundu@senate.gov.ng",
    status: "Active"
  },
  {
    id: "leg-achado-rep",
    name: "Hon. Austin Asema Achado",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Benue",
    constituency: "Gwer East/Gwer West",
    party: PoliticalParty.APC,
    engagementScore: 81,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 90,
    motionsPresentedCount: 8,
    districtOfficeEmail: "a.achado@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-gwalabe-rep",
    name: "Hon. Auwalu Abdu Gwalabe",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Bauchi",
    constituency: "Katagum",
    party: PoliticalParty.PDP,
    engagementScore: 82,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 91,
    motionsPresentedCount: 9,
    districtOfficeEmail: "a.gwalabe@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-abiante-rep",
    name: "Hon. Awaji-inombek Dagomie Abiante",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Rivers",
    constituency: "Opobo/Nkoro/Andoni",
    party: PoliticalParty.PDP,
    engagementScore: 86,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 93,
    motionsPresentedCount: 16,
    districtOfficeEmail: "d.abiante@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-alao-rep",
    name: "Hon. Ayodeji Alao",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Oyo",
    constituency: "Ogbomoso North/Ogbomoso South/Orire",
    party: PoliticalParty.APC,
    engagementScore: 81,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 90,
    motionsPresentedCount: 6,
    districtOfficeEmail: "a.alao@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-adefiranye-rep",
    name: "Hon. Ayodele Adefiranye",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Ondo",
    constituency: "Ileoluji/Okeigbo/Odigbo",
    party: PoliticalParty.APC,
    engagementScore: 82,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 90,
    motionsPresentedCount: 7,
    districtOfficeEmail: "a.adefiranye@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-dampar-rep",
    name: "Hon. Ayuba Dampar",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Taraba",
    constituency: "Ibi/Wukari",
    party: PoliticalParty.APC,
    engagementScore: 80,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 89,
    motionsPresentedCount: 5,
    districtOfficeEmail: "a.dampar@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-benson-rep-2",
    name: "Hon. Babajimi Adegoke Benson",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Lagos",
    constituency: "Ikorodu",
    party: PoliticalParty.APC,
    engagementScore: 91,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 96,
    motionsPresentedCount: 17,
    districtOfficeEmail: "j.benson@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-hussaini-sen",
    name: "Sen. Babangida Hussaini",
    title: "Senator",
    chamber: Chamber.SENATE,
    state: "Jigawa",
    constituency: "JIGAWA NORTH - WEST",
    party: PoliticalParty.APC,
    engagementScore: 85,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 92,
    motionsPresentedCount: 11,
    districtOfficeEmail: "b.hussaini@senate.gov.ng",
    status: "Active"
  },
  {
    id: "leg-aminu-rep",
    name: "Hon. Balele Aminu",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Katsina",
    constituency: "Dutsin-ma/Kurfi",
    party: PoliticalParty.APC,
    engagementScore: 82,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 91,
    motionsPresentedCount: 9,
    districtOfficeEmail: "a.balele@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-salam-rep-2",
    name: "Hon. Bamidele Salam",
    title: "Honourable",
    chamber: Chamber.HOUSE_OF_REPS,
    state: "Osun",
    constituency: "Ede North/Ede South/Egbedore/Ejigbo",
    party: PoliticalParty.PDP,
    engagementScore: 87,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 94,
    motionsPresentedCount: 18,
    districtOfficeEmail: "b.salam@nass.gov.ng",
    status: "Active"
  },
  {
    id: "leg-banigo-sen",
    name: "Sen. Banigo, Ipalibo Harry",
    title: "Senator",
    chamber: Chamber.SENATE,
    state: "Rivers",
    constituency: "RIVERS WEST",
    party: PoliticalParty.PDP,
    engagementScore: 84,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 92,
    motionsPresentedCount: 13,
    districtOfficeEmail: "h.banigo@senate.gov.ng",
    status: "Active"
  },
  {
    id: "leg-jibrin-sen",
    name: "Sen. Barau Jibrin",
    title: "Senator",
    chamber: Chamber.SENATE,
    state: "Kano",
    constituency: "Kano North",
    party: PoliticalParty.APC,
    engagementScore: 92,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 97,
    motionsPresentedCount: 18,
    districtOfficeEmail: "j.barau@senate.gov.ng",
    status: "Active"
  },
  {
    id: "leg-mpigi-sen",
    name: "Sen. Barinada Barry Mpigi",
    title: "Senator",
    chamber: Chamber.SENATE,
    state: "Rivers",
    constituency: "RIVERS SOUTH EAST",
    party: PoliticalParty.PDP,
    engagementScore: 85,
    avatarUrl: "",
    billsSponsored: [],
    attendanceRate: 91,
    motionsPresentedCount: 12,
    districtOfficeEmail: "b.mpigi@senate.gov.ng",
    status: "Active"
  }
];
